create database AgendaEventos;gouse AgendaEventos;gocreate table Categorias (ID int identity primary key,Nome nvarchar(100) not null);create table Palestrantes (ID int identity primary key,Nome nvarchar(120) not null,BioCurta nvarchar(300) null);create table Eventos (ID int identity primary key,IDCategoria int not null foreign key references Categorias(ID),IDPalestrante int not null foreign key references Palestrantes(ID),Titulo nvarchar(150) not null,DataHora datetime2 not null,Local nvarchar(120) not null,Descricao nvarchar(max) null,Destaque bit not null default 0);insert into Categorias (Nome) values (N'Tecnologia');insert into Categorias (Nome) values (N'Economia');insert into Categorias (Nome) values (N'Saúde');insert into Palestrantes (Nome, BioCurta) values (N'Guilherme Autulo', null);insert into Palestrantes (Nome, BioCurta) values (N'Ana Clara', N'Médica e pesquisadora em saúde pública.');insert into Palestrantes (Nome, BioCurta) values (N'Rafael Ferreira', N'Economista e consultor financeiro para pequenas empresas.');insert into Palestrantes (Nome, BioCurta) values (N'Pedro Rocha', null);insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (1, 1, N'Introdução ao C#', '2026-10-10 19:00', N'Unifev - Câmpus Cidade Universitária', N'Primeiros passos na linguagem C#.', 1);insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (2, 3, N'Finanças Pessoais', '2026-09-20 20:30',N'Unifev - Câmpus Centro', N'Como organizar o seu dinheiro.', 0);insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (3, 2, N'Saúde Mental no Trabalho', '2026-11-19 15:00',N'Concha Acústica', N'Prevenção de burnout na atualidade', 1);insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (1, 1, N'ASP.NET MVC na Prática', '2026-10-25 19:30',
N'Unifev - Câmpus Cidade Universitária', N'Criando um sistema web completo com MVC e Entity Framework.', 1);

insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (2, 3, N'Investimentos para Iniciantes', '2026-12-05 10:00',
N'Unifev - Câmpus Centro', N'Renda fixa, renda variável e como começar a investir.', 0);

insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (2, 3, N'Alimentação Saudável', '2026-08-14 16:00',
N'Concha Acústica', null, 0);

insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (1, 4, N'Banco de Dados com C#', '2026-11-08 20:00',
N'Unifev - Câmpus Cidade Universitária', N'Conectando aplicações C# ao SQL Server.', 0);

insert into Eventos (IDCategoria, IDPalestrante, Titulo, DataHora, Local, Descricao, Destaque) values (2, 4, N'Economia Brasileira em 2026', '2026-07-30 19:00',
N'Unifev - Câmpus Centro', N'Panorama da economia e perspectivas para o próximo ano.', 0);select * from Categoriasselect * from Palestrantesselect * from Eventos